[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
; monitor_speed = 9600
; monitor_echo = yes
; monitor_filters = send_on_enter

; Flags de depuración (descomentar una línea para habilitar el modo correspondiente):
; build_flags = -D DEBUG_MOTORS
; build_flags = -D DEBUG_SENSORS
